export const ENV_KEYS = {
  SUPABASE_URL: 'SUPABASE_URL',
  SUPABASE_ANON_KEY: 'SUPABASE_ANON_KEY',
  SUPABASE_SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
  VITE_SUPABASE_URL: 'VITE_SUPABASE_URL',
  VITE_SUPABASE_ANON_KEY: 'VITE_SUPABASE_ANON_KEY',
  NODE_ENV: 'NODE_ENV',
} as const

