import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync('src/routes/pegawai/dokumen/aju.tsx', 'utf8')
const fungsiTanggalSource = readFileSync('src/components/dokumen/form/StepFungsiTanggal.tsx', 'utf8')
const kegiatanSource = readFileSync('src/components/dokumen/form/StepKegiatan.tsx', 'utf8')
const karakteristikSource = readFileSync('src/components/dokumen/form/StepKarakteristik.tsx', 'utf8')
const komponenSource = readFileSync('src/components/dokumen/form/StepKomponen.tsx', 'utf8')
const namaDokumenSource = readFileSync('src/components/dokumen/form/StepNamaDokumen.tsx', 'utf8')
const jenisPermintaanSource = readFileSync('src/components/dokumen/form/StepJenisPermintaan.tsx', 'utf8')
const kategoriPermintaanSource = readFileSync('src/components/dokumen/form/StepKategoriPermintaan.tsx', 'utf8')
const uploadSource = readFileSync('src/components/dokumen/form/StepUploadLampiran.tsx', 'utf8')
const stepReviewSource = readFileSync('src/components/dokumen/form/StepReview.tsx', 'utf8')
const kelengkapanSource = readFileSync('src/components/dokumen/KelengkapanChecklist.tsx', 'utf8')
const uploadButtonSource = readFileSync('src/components/dokumen/FileUploadButton.tsx', 'utf8')
const reviewSource = readFileSync('src/components/dokumen/ReviewSummary.tsx', 'utf8')
const sidebarSource = readFileSync('src/components/layout/AppSidebar.tsx', 'utf8')

describe('Phase 15L.1 Ajukan Dokumen parity source guard', () => {
  it('uses three grouped presentation stages with confirmation and an in-page success state', () => {
    expect(source).toContain("'Informasi Dasar'")
    expect(source).toContain("'Unggah Dokumen'")
    expect(source).toContain("'Tinjauan'")
    expect(source).toContain('Ajukan dokumen ini?')
    expect(source).toContain('Pastikan jenis permintaan, kegiatan, nominal realisasi, dan kelengkapan sudah benar.')
    expect(source).toContain('setSubmittedDocument(response.dokumen)')
    expect(source).toContain('Lihat Daftar Dokumen')
    expect(source).toContain('Ajukan Dokumen Lain')
    expect(source).toContain('Lihat Detail Dokumen')
    expect(source).toContain('useAppToast()')
    expect(source).toContain('submitInFlightRef.current')
  })

  it('keeps the visual parity pass bounded to response-backed Ajukan presentation', () => {
    expect(source).toContain('Progress Pengajuan')
    expect(source).toContain('MAJOR_STEP_SUBTITLES')
    expect(source).toContain('Konsekuensi pengajuan')
    expect(source).toContain('Pengajuan Berhasil')
    expect(source).toContain('file lampiran')
    expect(source).toContain('Tahap berikutnya:')
    expect(source).toContain('max-w-3xl flex-col items-center text-center')
    expect(source).not.toContain('Semua tahap selesai')
    expect(source).not.toContain('Dokumen diproses')
    expect(source).not.toContain('Pengajuan selesai')
    expect(source).toContain('<ConfirmDialog')
    expect(source).not.toContain('<AppDialog')
    expect(source).not.toContain('#/routes/api')
  })

  it('keeps Step 1 visually direct without nested grouped-section cards', () => {
    expect(source).not.toContain('GroupedFormSection')
    expect(source).not.toContain('Perlu dilengkapi')
    expect(source).toContain('showTanggal={false}')
    expect(source).toContain('showFungsi={false}')
    expect(source).toContain('rounded-t-[1.5rem] bg-gradient-to-r from-[#F97316] to-[#FB923C]')
    expect(source).toContain('<div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_18rem]">')
    expect(source).toContain('<div className="min-w-0 px-1 py-1 sm:px-2">')
    expect(source).not.toContain('DisabledFieldPlaceholder')
    expect(source).not.toContain('Pilih fungsi terlebih dahulu')
    expect(source).not.toContain('Pilih jenis permintaan terlebih dahulu')

    expect(fungsiTanggalSource).toContain('Pilih Fungsi')
    expect(fungsiTanggalSource).toContain('Pilih Tanggal Laporan')
    expect(fungsiTanggalSource).toContain('aria-pressed={selected}')
    expect(kegiatanSource).toContain('Pilih Kegiatan')
    expect(kegiatanSource).toContain('-- Pilih Kegiatan --')
    expect(kegiatanSource).toContain('value={kegiatanId || null}')
    expect(kegiatanSource).toContain(": '-- Pilih Kegiatan --'")
    expect(karakteristikSource).toContain('Karakteristik Dokumen')
    expect(karakteristikSource).toContain('aria-pressed={!isNonMaterial}')
    expect(karakteristikSource).toContain('aria-pressed={isNonMaterial}')
    expect(karakteristikSource).not.toContain('type="checkbox"')
    expect(komponenSource).toContain('Pilih Komponen')
    expect(komponenSource).toContain('-- Pilih Komponen --')
    expect(komponenSource).toContain('value={komponenId || null}')
    expect(namaDokumenSource).toContain('Nama Dokumen')
    expect(jenisPermintaanSource).toContain('Pilih Jenis Permintaan')
    expect(jenisPermintaanSource).toContain('-- Pilih Jenis Permintaan --')
    expect(jenisPermintaanSource).toContain('value={jenisPermintaanId || null}')
    expect(jenisPermintaanSource).toContain(": '-- Pilih Jenis Permintaan --'")
    expect(kategoriPermintaanSource).toContain('Pilih Kategori Permintaan')
    expect(kategoriPermintaanSource).toContain('-- Pilih Kategori Permintaan --')
    expect(kategoriPermintaanSource).toContain('value={kategoriPermintaanId || null}')
    expect(kategoriPermintaanSource).toContain(": '-- Pilih Kategori Permintaan --'")
  })

  it('RP-04: keeps Komponen/Nama Dokumen sections mounted (hidden, not unmounted) on characteristic toggle', () => {
    // Regression guard: swapping these via `isNonMaterial ? <A/> : <B/>` unmounted whichever Select
    // was open mid-interaction and left Base UI's popup/scroll-lock guard stuck (RP-04 bug repro).
    // The fix keeps StepKomponen/StepNamaDokumen always mounted once Kegiatan is picked, toggling
    // visibility with the `hidden` attribute based on `isNonMaterial` instead. Material is the
    // toggle's default value, so Komponen is visible immediately (no extra click required).
    expect(source).toContain('<div hidden={isNonMaterial}>')
    expect(source).toContain('<div hidden={!isNonMaterial}>')
    expect(source).not.toMatch(/isNonMaterial\s*\?\s*<StepNamaDokumen/)
    expect(source).not.toMatch(/isNonMaterial\s*\?\s*\(?\s*<StepKomponen/)
  })

  it('keeps Step 2 compact and restores a compact grouped Step 3 with a page-local warm palette', () => {
    expect(uploadSource).toContain('const contextParts = [')
    expect(uploadSource).toContain('Status kegiatan Anda:')
    expect(uploadSource).toContain('<KelengkapanChecklist')
    expect(uploadSource).toContain('<textarea')
    expect(uploadSource).toContain('Masukkan keterangan detail dokumen (opsional)...')
    expect(uploadSource).not.toContain('Konteks Kelengkapan')
    expect(uploadSource).not.toContain('Lampiran Dokumen')

    expect(kelengkapanSource).toContain('Dokumen Wajib')
    expect(kelengkapanSource).toContain('Dokumen Pendukung')
    expect(kelengkapanSource).toContain('Tambahkan dokumen pendukung untuk melengkapi')
    expect(kelengkapanSource).toContain('Tambah Dokumen Pendukung')
    expect(kelengkapanSource).toContain('border border-dashed border-orange-300')
    expect(kelengkapanSource).toContain('DOCUMENT_UPLOAD_HELPER_TEXT')
    expect(kelengkapanSource).not.toContain('Dokumen Opsional')
    expect(kelengkapanSource).not.toContain('Dokumen Tambahan')
    expect(kelengkapanSource).not.toContain('Tambah Dokumen Opsional')
    expect(kelengkapanSource).toContain('const [showAddForm, setShowAddForm] = useState(false)')
    expect(kelengkapanSource).not.toContain('Progress Lampiran')
    expect(kelengkapanSource).not.toContain('Kelengkapan Admin')

    expect(reviewSource).toContain('Ringkasan Pengajuan')
    expect(reviewSource).toContain('title="Informasi Dokumen"')
    expect(reviewSource).toContain('title="Karakteristik Dokumen"')
    expect(reviewSource).toContain('Kelengkapan Lampiran')
    expect(reviewSource).toContain('bg-[#FFF3D6]')
    expect(stepReviewSource).toContain('<ReviewSummary')
    expect(stepReviewSource).not.toContain('Siap diajukan')
    expect(stepReviewSource).not.toContain('Hasil Pengajuan')
    expect(stepReviewSource).not.toContain('Konfirmasi Akhir')
    expect(stepReviewSource).not.toContain('stepCount')

    expect(source).toContain('bg-[#FFF9F4]')
    expect(source).toContain('from-[#F97316] to-[#FB923C]')
    expect(source).toContain('bg-[#F97316]')
    expect(source).not.toContain('bg-[#FF6701]')
    expect(source).toContain('Periksa Sebelum Mengajukan')
    expect(source).toContain('Baca kembali seluruh isian dan pastikan data serta lampiran sudah benar sebelum mengajukan dokumen.')
    expect(source).not.toContain('Format Tambahan')
    expect(source).toContain('to="/pegawai"')
    expect(source).toContain('aria-label="Kembali ke dashboard pegawai"')
    expect(source).toContain('xl:grid-cols-[minmax(0,1fr)_18rem]')
    expect(sidebarSource).toContain("const useCompactDesktopWidth = pathname === '/pegawai/dokumen/aju'")
    expect(sidebarSource).toContain("useCompactDesktopWidth ? 'lg:w-56 xl:w-60' : 'lg:w-60 xl:w-60'")
    expect(source).toContain('border-[#FDBA8C] bg-[#FFF1E7]')
    expect(source).not.toContain('Bagian {step} dari {stepLabels.length}')
    expect(source).not.toContain('Sebelum melanjutkan')
    expect(source).toContain('Selesai')
    expect(source).toContain('Aktif')
    expect(source).not.toContain('bg-[#E98B52]')
    expect(source).not.toContain('bg-orange-500')
  })

  it('preserves the submit endpoint and business payload identifiers', () => {
    expect(source).toContain("apiMutation<SubmitResponse>('/api/dokumen/submit'")
    expect(source).toContain('nominal_realisasi: nominalValue')
    expect(source).toContain('is_non_material: isNonMaterial')
    expect(source).toContain('namaDokumen: isNonMaterial ? namaDokumen.trim() : undefined')
    expect(source).toContain('komponenId: !isNonMaterial ? selectedKomponenId : undefined')
    expect(source).toContain('jenisPermintaanId: !isNonMaterial ? selectedJenisPermintaanId : undefined')
    expect(source).toContain('kategoriPermintaanId: !isNonMaterial ? selectedKategoriPermintaanId : undefined')
    expect(source).toContain('detailPermintaanId: !isNonMaterial ? selectedDetailPermintaanId : undefined')
  })

  it('mirrors the Revisi-style pending upload row and Ajukan unsaved guard without backend changes', () => {
    expect(source).toContain('useBlocker')
    expect(source).toContain('leaveBlocker.status === \'blocked\'')
    expect(source).toContain('Keluar tanpa menyimpan?')
    expect(source).toContain('Perubahan yang belum disimpan akan hilang.')
    expect(source).toContain('Tetap di halaman')
    expect(source).toContain('Keluar tanpa menyimpan')
    expect(source).toContain('beforeunload')
    expect(source).toContain('setAttachmentDirty(false)')
    expect(source).toContain('onAttachmentDirtyChange={setAttachmentDirty}')
    expect(source).toContain('lampiranUrls={lampiranUrls}')

    expect(uploadSource).toContain('initialLampirans={lampiranUrls}')
    expect(uploadSource).toContain('onDirtyChange={onAttachmentDirtyChange}')
    expect(kelengkapanSource).toContain('onDirtyChange?: (dirty: boolean) => void')
    expect(kelengkapanSource).toContain('initialLampiran={uploaded}')
    expect(kelengkapanSource).toContain('bg-emerald-50/45')
    expect(kelengkapanSource).toContain('extractFilenameFromPath')
    expect(kelengkapanSource).toContain('getUploadedFilename(uploaded)')
    expect(kelengkapanSource).toContain('sm:w-auto')
    expect(kelengkapanSource).not.toContain('Progress Lampiran')

    expect(uploadButtonSource).toContain('getSignedUrlDirectResult')
    expect(uploadButtonSource).toContain('fetchFileBlobWithSignedUrl')
    expect(uploadButtonSource).toContain('getDocumentUploadValidationUiMessage')
    expect(uploadButtonSource).toContain('border border-amber-200 bg-[#FFF8EA]')
    expect(uploadButtonSource).toContain('validationUi.actionLabel')
    expect(uploadButtonSource).not.toContain('border border-red-100 bg-red-50 p-2.5')
    expect(uploadButtonSource).toContain('Pratinjau')
    expect(uploadButtonSource).toContain('Ganti')
    expect(uploadButtonSource).toContain('Hapus')
    expect(uploadButtonSource).toContain('text-error hover:bg-red-50 hover:text-red-700')
    expect(uploadButtonSource).toContain('extractFilenameFromPath')
    expect(uploadButtonSource).toContain('rounded-2xl')
    expect(uploadButtonSource).not.toContain('/api/dokumen/submit')
  })

  it('does not introduce forbidden Ajukan terminology or features', () => {
    expect(source).not.toContain('Simpan Draft')
    expect(source).not.toContain('Nomor Surat')
    expect(source).not.toContain('Cari Arsip')
    expect(source).not.toContain('Laporan Klasifikasi')
  })
})
