import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync('src/routes/ppk/dokumen/$id/resubmit.tsx', 'utf8')

describe('Phase 15L.2C PPK resubmit visual parity source guard', () => {
  it('uses approved Revisi/Ajukan visual patterns on the PPK resubmit page', () => {
    expect(source).toContain("'Metadata & Ringkasan Revisi'")
    expect(source).toContain("'Metadata & Lampiran'")
    expect(source).toContain("'Riwayat'")
    expect(source).toContain("activeTab === 'edit' ? 'block' : 'hidden'")
    expect(source).toContain("{activeTab === 'history' && <ActivityLog dokumenId={id} />}")
    expect(source).toContain('Catatan dari PPSPM')
    expect(source).toContain('Aksi Revisi PPK')
    expect(source).toContain('min-h-full bg-[#FFF9F4] px-4 py-4 sm:px-6 lg:px-7 lg:py-5')
    expect(source).toContain('mx-auto max-w-[92rem] space-y-4')
    expect(source).toContain('flex size-10 shrink-0 items-center justify-center rounded-full bg-zinc-100')
    expect(source).toContain('xl:grid-cols-[minmax(0,1fr)_18rem]')
    expect(source).toContain('rounded-t-[1.5rem] bg-gradient-to-r from-[#F97316] to-[#FB923C] px-4 py-4')
    expect(source).toContain('rounded-b-[1.5rem] border border-t-0 border-[#F1E5DA] bg-[#FFFDF9] p-4 sm:p-5')
    expect(source).toContain('border-rose-100 bg-rose-50/55 p-3')
    expect(source).toContain('space-y-2.5 px-0.5 py-1')
    expect(source).toContain('h-10 w-full gap-2 rounded-xl bg-[#FF5A00] text-sm font-bold')
    expect(source).toContain("label === 'Nominal Realisasi' ? 'text-[#FF5A00]' : 'text-zinc-950'")
    expect(source).toContain('showAsRevision ? \'text-rose-600\'')
    expect(source).toContain('showAsRevisionPpk')
    expect(source).not.toContain('rounded-t-2xl bg-gradient-to-r from-[#F97316] to-[#FB923C] px-3 py-2.5')
    expect(source).not.toContain('rounded-b-2xl border border-t-0 border-[#F1E5DA]')
    expect(source).not.toContain("'Review & Ajukan'")
    expect(source).not.toContain('tab.icon')
  })

  it('adds approved confirmation, success, toast, and unsaved guard patterns', () => {
    expect(source).toContain('<AppDialog')
    expect(source).toContain('useAppToast()')
    expect(source).toContain('useBlocker')
    expect(source).toContain('beforeunload')
    expect(source).toContain('Keluar tanpa menyimpan?')
    expect(source).toContain('Perubahan yang belum disimpan akan hilang.')
    expect(source).toContain('Tetap di halaman')
    expect(source).toContain('Keluar tanpa menyimpan')
    expect(source).toContain('Ajukan ulang dokumen?')
    expect(source).toContain('Ajukan ulang tanpa perubahan?')
    expect(source).toContain('Revisi Berhasil Dikirim')
    expect(source).toContain('Revisi PPK berhasil diajukan ulang')
    expect(source).toContain('Lihat Daftar Revisi')
    expect(source).toContain('Lihat Detail Dokumen')
    expect(source).toContain('Kembalikan ke Pegawai?')
    expect(source).toContain('<ChevronLeft size={15} />\n                  Kembali')
    expect(source).toContain('border-[#F0E1D5] bg-[#FFFDF9] text-sm font-bold text-zinc-950')
    expect(source).toContain('setSubmitRequestSignal(current => current + 1)')
    expect(source).toContain('setCancelRequestSignal(current => current + 1)')
    expect(source).not.toContain('Batal')
  })

  it('preserves PPK resubmit endpoint sequence and payload shape', () => {
    const patchIndex = source.indexOf("apiMutation(`/api/ppk/resubmit/${id}`, {\n          method: 'PATCH'")
    const submitIndex = source.indexOf("apiMutation(`/api/ppk/resubmit/${id}`, {\n          method: 'POST'")

    expect(source).toContain("apiFetch<{ dokumen: DokumenRow }>(`/ppk/resubmit/${id}`)")
    expect(patchIndex).toBeGreaterThan(-1)
    expect(submitIndex).toBeGreaterThan(patchIndex)
    expect(source).toContain('body: {\n            lampiranUrls: data.lampiranUrls,\n            nominalRealisasi: data.nominalRealisasi,\n          }')
    expect(source).toContain("apiMutation(`/api/ppk/kembalikan/${id}`, { method: 'POST' })")
    expect(source).not.toContain('/api/dokumen/${id}/submit')
    expect(source).not.toContain("apiMutation(`/api/dokumen/${id}`")
    expect(source).not.toContain('#/routes/api')
    expect(source).not.toContain('/api/upload')
  })

  it('keeps AttachmentEditor as upload behavior authority', () => {
    expect(source).toContain('<AttachmentEditor')
    expect(source).toContain('confirmBeforeSubmit={confirmBeforeSubmit}')
    expect(source).toContain('hideDefaultActions')
    expect(source).toContain('submitRequestSignal={submitRequestSignal}')
    expect(source).toContain('cancelRequestSignal={cancelRequestSignal}')
    expect(source).toContain('onDirtyChange={setAttachmentDirty}')
    expect(source).toContain('confirmIfDirty={confirmIfDirty}')
    expect(source).toContain('submitLabel="Ajukan Ulang ke PPSPM"')
    expect(source).not.toContain('extraActions=')
    expect(source).not.toContain('AttachmentViewer')
  })

  it('does not introduce forbidden PPK resubmit behavior changes', () => {
    expect(source).not.toContain('Simpan Draft')
    expect(source).not.toContain('Nomor Surat')
    expect(source).not.toContain('Nomor SPM')
    expect(source).not.toContain('Cari Arsip')
    expect(source).not.toContain('Laporan Klasifikasi')
    expect(source).not.toContain('supabase')
    expect(source).not.toContain('package.json')
  })
})
