/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PpkRouteImport } from './routes/ppk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as DokumenRouteImport } from './routes/dokumen'
import { Route as BendaharaRouteImport } from './routes/bendahara'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArsiparisIndexRouteImport } from './routes/arsiparis.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DokumenSayaRouteImport } from './routes/dokumen/saya'
import { Route as DokumenAjuRouteImport } from './routes/dokumen/aju'
import { Route as DokumenAjiRouteImport } from './routes/dokumen/aji'
import { Route as DokumenIdRouteImport } from './routes/dokumen.$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiMasterKelengkapanRouteImport } from './routes/api/master-kelengkapan'
import { Route as ApiMasterKegiatanRouteImport } from './routes/api/master-kegiatan'
import { Route as ApiMasterFungsiRouteImport } from './routes/api/master-fungsi'
import { Route as ApiDokumenIndexRouteImport } from './routes/api/dokumen/index'
import { Route as AdminMasterDataIndexRouteImport } from './routes/admin.master-data.index'
import { Route as DokumenIdEditRouteImport } from './routes/dokumen.$id.edit'
import { Route as ApiMasterKelengkapanIdRouteImport } from './routes/api/master-kelengkapan.$id'
import { Route as ApiMasterKegiatanIdRouteImport } from './routes/api/master-kegiatan.$id'
import { Route as ApiMasterFungsiIdRouteImport } from './routes/api/master-fungsi.$id'
import { Route as ApiDokumenSubmitRouteImport } from './routes/api/dokumen/submit'
import { Route as ApiDokumenIdRouteImport } from './routes/api/dokumen.$id'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthRoleSwitchRouteImport } from './routes/api/auth/role-switch'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AdminMasterDataUserRouteImport } from './routes/admin.master-data.user'
import { Route as AdminMasterDataKelengkapanRouteImport } from './routes/admin.master-data.kelengkapan'
import { Route as AdminMasterDataKegiatanRouteImport } from './routes/admin.master-data.kegiatan'
import { Route as AdminMasterDataFungsiRouteImport } from './routes/admin.master-data.fungsi'
import { Route as ApiDokumenIdSubmitRouteImport } from './routes/api/dokumen.$id.submit'
import { Route as ApiDokumenIdDownloadLampiranIndexRouteImport } from './routes/api/dokumen.$id.download.$lampiranIndex'

const PpkRoute = PpkRouteImport.update({
  id: '/ppk',
  path: '/ppk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenRoute = DokumenRouteImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => rootRouteImport,
} as any)
const BendaharaRoute = BendaharaRouteImport.update({
  id: '/bendahara',
  path: '/bendahara',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsiparisIndexRoute = ArsiparisIndexRouteImport.update({
  id: '/arsiparis/',
  path: '/arsiparis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenSayaRoute = DokumenSayaRouteImport.update({
  id: '/saya',
  path: '/saya',
  getParentRoute: () => DokumenRoute,
} as any)
const DokumenAjuRoute = DokumenAjuRouteImport.update({
  id: '/aju',
  path: '/aju',
  getParentRoute: () => DokumenRoute,
} as any)
const DokumenAjiRoute = DokumenAjiRouteImport.update({
  id: '/aji',
  path: '/aji',
  getParentRoute: () => DokumenRoute,
} as any)
const DokumenIdRoute = DokumenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DokumenRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterKelengkapanRoute = ApiMasterKelengkapanRouteImport.update({
  id: '/api/master-kelengkapan',
  path: '/api/master-kelengkapan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterKegiatanRoute = ApiMasterKegiatanRouteImport.update({
  id: '/api/master-kegiatan',
  path: '/api/master-kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterFungsiRoute = ApiMasterFungsiRouteImport.update({
  id: '/api/master-fungsi',
  path: '/api/master-fungsi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDokumenIndexRoute = ApiDokumenIndexRouteImport.update({
  id: '/api/dokumen/',
  path: '/api/dokumen/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataIndexRoute = AdminMasterDataIndexRouteImport.update({
  id: '/admin/master-data/',
  path: '/admin/master-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenIdEditRoute = DokumenIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DokumenIdRoute,
} as any)
const ApiMasterKelengkapanIdRoute = ApiMasterKelengkapanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMasterKelengkapanRoute,
} as any)
const ApiMasterKegiatanIdRoute = ApiMasterKegiatanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMasterKegiatanRoute,
} as any)
const ApiMasterFungsiIdRoute = ApiMasterFungsiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMasterFungsiRoute,
} as any)
const ApiDokumenSubmitRoute = ApiDokumenSubmitRouteImport.update({
  id: '/api/dokumen/submit',
  path: '/api/dokumen/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDokumenIdRoute = ApiDokumenIdRouteImport.update({
  id: '/api/dokumen/$id',
  path: '/api/dokumen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoleSwitchRoute = ApiAuthRoleSwitchRouteImport.update({
  id: '/api/auth/role-switch',
  path: '/api/auth/role-switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataUserRoute = AdminMasterDataUserRouteImport.update({
  id: '/admin/master-data/user',
  path: '/admin/master-data/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataKelengkapanRoute =
  AdminMasterDataKelengkapanRouteImport.update({
    id: '/admin/master-data/kelengkapan',
    path: '/admin/master-data/kelengkapan',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMasterDataKegiatanRoute = AdminMasterDataKegiatanRouteImport.update({
  id: '/admin/master-data/kegiatan',
  path: '/admin/master-data/kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataFungsiRoute = AdminMasterDataFungsiRouteImport.update({
  id: '/admin/master-data/fungsi',
  path: '/admin/master-data/fungsi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDokumenIdSubmitRoute = ApiDokumenIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiDokumenIdRoute,
} as any)
const ApiDokumenIdDownloadLampiranIndexRoute =
  ApiDokumenIdDownloadLampiranIndexRouteImport.update({
    id: '/download/$lampiranIndex',
    path: '/download/$lampiranIndex',
    getParentRoute: () => ApiDokumenIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bendahara': typeof BendaharaRoute
  '/dokumen': typeof DokumenRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/ppk': typeof PpkRoute
  '/api/master-fungsi': typeof ApiMasterFungsiRouteWithChildren
  '/api/master-kegiatan': typeof ApiMasterKegiatanRouteWithChildren
  '/api/master-kelengkapan': typeof ApiMasterKelengkapanRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/dokumen/$id': typeof DokumenIdRouteWithChildren
  '/dokumen/aji': typeof DokumenAjiRoute
  '/dokumen/aju': typeof DokumenAjuRoute
  '/dokumen/saya': typeof DokumenSayaRoute
  '/admin/': typeof AdminIndexRoute
  '/arsiparis/': typeof ArsiparisIndexRoute
  '/admin/master-data/fungsi': typeof AdminMasterDataFungsiRoute
  '/admin/master-data/kegiatan': typeof AdminMasterDataKegiatanRoute
  '/admin/master-data/kelengkapan': typeof AdminMasterDataKelengkapanRoute
  '/admin/master-data/user': typeof AdminMasterDataUserRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/role-switch': typeof ApiAuthRoleSwitchRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/dokumen/$id': typeof ApiDokumenIdRouteWithChildren
  '/api/dokumen/submit': typeof ApiDokumenSubmitRoute
  '/api/master-fungsi/$id': typeof ApiMasterFungsiIdRoute
  '/api/master-kegiatan/$id': typeof ApiMasterKegiatanIdRoute
  '/api/master-kelengkapan/$id': typeof ApiMasterKelengkapanIdRoute
  '/dokumen/$id/edit': typeof DokumenIdEditRoute
  '/admin/master-data/': typeof AdminMasterDataIndexRoute
  '/api/dokumen/': typeof ApiDokumenIndexRoute
  '/api/dokumen/$id/submit': typeof ApiDokumenIdSubmitRoute
  '/api/dokumen/$id/download/$lampiranIndex': typeof ApiDokumenIdDownloadLampiranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bendahara': typeof BendaharaRoute
  '/dokumen': typeof DokumenRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/ppk': typeof PpkRoute
  '/api/master-fungsi': typeof ApiMasterFungsiRouteWithChildren
  '/api/master-kegiatan': typeof ApiMasterKegiatanRouteWithChildren
  '/api/master-kelengkapan': typeof ApiMasterKelengkapanRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/dokumen/$id': typeof DokumenIdRouteWithChildren
  '/dokumen/aji': typeof DokumenAjiRoute
  '/dokumen/aju': typeof DokumenAjuRoute
  '/dokumen/saya': typeof DokumenSayaRoute
  '/admin': typeof AdminIndexRoute
  '/arsiparis': typeof ArsiparisIndexRoute
  '/admin/master-data/fungsi': typeof AdminMasterDataFungsiRoute
  '/admin/master-data/kegiatan': typeof AdminMasterDataKegiatanRoute
  '/admin/master-data/kelengkapan': typeof AdminMasterDataKelengkapanRoute
  '/admin/master-data/user': typeof AdminMasterDataUserRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/role-switch': typeof ApiAuthRoleSwitchRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/dokumen/$id': typeof ApiDokumenIdRouteWithChildren
  '/api/dokumen/submit': typeof ApiDokumenSubmitRoute
  '/api/master-fungsi/$id': typeof ApiMasterFungsiIdRoute
  '/api/master-kegiatan/$id': typeof ApiMasterKegiatanIdRoute
  '/api/master-kelengkapan/$id': typeof ApiMasterKelengkapanIdRoute
  '/dokumen/$id/edit': typeof DokumenIdEditRoute
  '/admin/master-data': typeof AdminMasterDataIndexRoute
  '/api/dokumen': typeof ApiDokumenIndexRoute
  '/api/dokumen/$id/submit': typeof ApiDokumenIdSubmitRoute
  '/api/dokumen/$id/download/$lampiranIndex': typeof ApiDokumenIdDownloadLampiranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bendahara': typeof BendaharaRoute
  '/dokumen': typeof DokumenRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/ppk': typeof PpkRoute
  '/api/master-fungsi': typeof ApiMasterFungsiRouteWithChildren
  '/api/master-kegiatan': typeof ApiMasterKegiatanRouteWithChildren
  '/api/master-kelengkapan': typeof ApiMasterKelengkapanRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/dokumen/$id': typeof DokumenIdRouteWithChildren
  '/dokumen/aji': typeof DokumenAjiRoute
  '/dokumen/aju': typeof DokumenAjuRoute
  '/dokumen/saya': typeof DokumenSayaRoute
  '/admin/': typeof AdminIndexRoute
  '/arsiparis/': typeof ArsiparisIndexRoute
  '/admin/master-data/fungsi': typeof AdminMasterDataFungsiRoute
  '/admin/master-data/kegiatan': typeof AdminMasterDataKegiatanRoute
  '/admin/master-data/kelengkapan': typeof AdminMasterDataKelengkapanRoute
  '/admin/master-data/user': typeof AdminMasterDataUserRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/role-switch': typeof ApiAuthRoleSwitchRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/dokumen/$id': typeof ApiDokumenIdRouteWithChildren
  '/api/dokumen/submit': typeof ApiDokumenSubmitRoute
  '/api/master-fungsi/$id': typeof ApiMasterFungsiIdRoute
  '/api/master-kegiatan/$id': typeof ApiMasterKegiatanIdRoute
  '/api/master-kelengkapan/$id': typeof ApiMasterKelengkapanIdRoute
  '/dokumen/$id/edit': typeof DokumenIdEditRoute
  '/admin/master-data/': typeof AdminMasterDataIndexRoute
  '/api/dokumen/': typeof ApiDokumenIndexRoute
  '/api/dokumen/$id/submit': typeof ApiDokumenIdSubmitRoute
  '/api/dokumen/$id/download/$lampiranIndex': typeof ApiDokumenIdDownloadLampiranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bendahara'
    | '/dokumen'
    | '/forbidden'
    | '/login'
    | '/ppk'
    | '/api/master-fungsi'
    | '/api/master-kegiatan'
    | '/api/master-kelengkapan'
    | '/api/upload'
    | '/dokumen/$id'
    | '/dokumen/aji'
    | '/dokumen/aju'
    | '/dokumen/saya'
    | '/admin/'
    | '/arsiparis/'
    | '/admin/master-data/fungsi'
    | '/admin/master-data/kegiatan'
    | '/admin/master-data/kelengkapan'
    | '/admin/master-data/user'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/role-switch'
    | '/api/auth/session'
    | '/api/dokumen/$id'
    | '/api/dokumen/submit'
    | '/api/master-fungsi/$id'
    | '/api/master-kegiatan/$id'
    | '/api/master-kelengkapan/$id'
    | '/dokumen/$id/edit'
    | '/admin/master-data/'
    | '/api/dokumen/'
    | '/api/dokumen/$id/submit'
    | '/api/dokumen/$id/download/$lampiranIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bendahara'
    | '/dokumen'
    | '/forbidden'
    | '/login'
    | '/ppk'
    | '/api/master-fungsi'
    | '/api/master-kegiatan'
    | '/api/master-kelengkapan'
    | '/api/upload'
    | '/dokumen/$id'
    | '/dokumen/aji'
    | '/dokumen/aju'
    | '/dokumen/saya'
    | '/admin'
    | '/arsiparis'
    | '/admin/master-data/fungsi'
    | '/admin/master-data/kegiatan'
    | '/admin/master-data/kelengkapan'
    | '/admin/master-data/user'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/role-switch'
    | '/api/auth/session'
    | '/api/dokumen/$id'
    | '/api/dokumen/submit'
    | '/api/master-fungsi/$id'
    | '/api/master-kegiatan/$id'
    | '/api/master-kelengkapan/$id'
    | '/dokumen/$id/edit'
    | '/admin/master-data'
    | '/api/dokumen'
    | '/api/dokumen/$id/submit'
    | '/api/dokumen/$id/download/$lampiranIndex'
  id:
    | '__root__'
    | '/'
    | '/bendahara'
    | '/dokumen'
    | '/forbidden'
    | '/login'
    | '/ppk'
    | '/api/master-fungsi'
    | '/api/master-kegiatan'
    | '/api/master-kelengkapan'
    | '/api/upload'
    | '/dokumen/$id'
    | '/dokumen/aji'
    | '/dokumen/aju'
    | '/dokumen/saya'
    | '/admin/'
    | '/arsiparis/'
    | '/admin/master-data/fungsi'
    | '/admin/master-data/kegiatan'
    | '/admin/master-data/kelengkapan'
    | '/admin/master-data/user'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/role-switch'
    | '/api/auth/session'
    | '/api/dokumen/$id'
    | '/api/dokumen/submit'
    | '/api/master-fungsi/$id'
    | '/api/master-kegiatan/$id'
    | '/api/master-kelengkapan/$id'
    | '/dokumen/$id/edit'
    | '/admin/master-data/'
    | '/api/dokumen/'
    | '/api/dokumen/$id/submit'
    | '/api/dokumen/$id/download/$lampiranIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BendaharaRoute: typeof BendaharaRoute
  DokumenRoute: typeof DokumenRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  PpkRoute: typeof PpkRoute
  ApiMasterFungsiRoute: typeof ApiMasterFungsiRouteWithChildren
  ApiMasterKegiatanRoute: typeof ApiMasterKegiatanRouteWithChildren
  ApiMasterKelengkapanRoute: typeof ApiMasterKelengkapanRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArsiparisIndexRoute: typeof ArsiparisIndexRoute
  AdminMasterDataFungsiRoute: typeof AdminMasterDataFungsiRoute
  AdminMasterDataKegiatanRoute: typeof AdminMasterDataKegiatanRoute
  AdminMasterDataKelengkapanRoute: typeof AdminMasterDataKelengkapanRoute
  AdminMasterDataUserRoute: typeof AdminMasterDataUserRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRoleSwitchRoute: typeof ApiAuthRoleSwitchRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiDokumenIdRoute: typeof ApiDokumenIdRouteWithChildren
  ApiDokumenSubmitRoute: typeof ApiDokumenSubmitRoute
  AdminMasterDataIndexRoute: typeof AdminMasterDataIndexRoute
  ApiDokumenIndexRoute: typeof ApiDokumenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ppk': {
      id: '/ppk'
      path: '/ppk'
      fullPath: '/ppk'
      preLoaderRoute: typeof PpkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumen': {
      id: '/dokumen'
      path: '/dokumen'
      fullPath: '/dokumen'
      preLoaderRoute: typeof DokumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bendahara': {
      id: '/bendahara'
      path: '/bendahara'
      fullPath: '/bendahara'
      preLoaderRoute: typeof BendaharaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsiparis/': {
      id: '/arsiparis/'
      path: '/arsiparis'
      fullPath: '/arsiparis/'
      preLoaderRoute: typeof ArsiparisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumen/saya': {
      id: '/dokumen/saya'
      path: '/saya'
      fullPath: '/dokumen/saya'
      preLoaderRoute: typeof DokumenSayaRouteImport
      parentRoute: typeof DokumenRoute
    }
    '/dokumen/aju': {
      id: '/dokumen/aju'
      path: '/aju'
      fullPath: '/dokumen/aju'
      preLoaderRoute: typeof DokumenAjuRouteImport
      parentRoute: typeof DokumenRoute
    }
    '/dokumen/aji': {
      id: '/dokumen/aji'
      path: '/aji'
      fullPath: '/dokumen/aji'
      preLoaderRoute: typeof DokumenAjiRouteImport
      parentRoute: typeof DokumenRoute
    }
    '/dokumen/$id': {
      id: '/dokumen/$id'
      path: '/$id'
      fullPath: '/dokumen/$id'
      preLoaderRoute: typeof DokumenIdRouteImport
      parentRoute: typeof DokumenRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master-kelengkapan': {
      id: '/api/master-kelengkapan'
      path: '/api/master-kelengkapan'
      fullPath: '/api/master-kelengkapan'
      preLoaderRoute: typeof ApiMasterKelengkapanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master-kegiatan': {
      id: '/api/master-kegiatan'
      path: '/api/master-kegiatan'
      fullPath: '/api/master-kegiatan'
      preLoaderRoute: typeof ApiMasterKegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master-fungsi': {
      id: '/api/master-fungsi'
      path: '/api/master-fungsi'
      fullPath: '/api/master-fungsi'
      preLoaderRoute: typeof ApiMasterFungsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dokumen/': {
      id: '/api/dokumen/'
      path: '/api/dokumen'
      fullPath: '/api/dokumen/'
      preLoaderRoute: typeof ApiDokumenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data/': {
      id: '/admin/master-data/'
      path: '/admin/master-data'
      fullPath: '/admin/master-data/'
      preLoaderRoute: typeof AdminMasterDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumen/$id/edit': {
      id: '/dokumen/$id/edit'
      path: '/edit'
      fullPath: '/dokumen/$id/edit'
      preLoaderRoute: typeof DokumenIdEditRouteImport
      parentRoute: typeof DokumenIdRoute
    }
    '/api/master-kelengkapan/$id': {
      id: '/api/master-kelengkapan/$id'
      path: '/$id'
      fullPath: '/api/master-kelengkapan/$id'
      preLoaderRoute: typeof ApiMasterKelengkapanIdRouteImport
      parentRoute: typeof ApiMasterKelengkapanRoute
    }
    '/api/master-kegiatan/$id': {
      id: '/api/master-kegiatan/$id'
      path: '/$id'
      fullPath: '/api/master-kegiatan/$id'
      preLoaderRoute: typeof ApiMasterKegiatanIdRouteImport
      parentRoute: typeof ApiMasterKegiatanRoute
    }
    '/api/master-fungsi/$id': {
      id: '/api/master-fungsi/$id'
      path: '/$id'
      fullPath: '/api/master-fungsi/$id'
      preLoaderRoute: typeof ApiMasterFungsiIdRouteImport
      parentRoute: typeof ApiMasterFungsiRoute
    }
    '/api/dokumen/submit': {
      id: '/api/dokumen/submit'
      path: '/api/dokumen/submit'
      fullPath: '/api/dokumen/submit'
      preLoaderRoute: typeof ApiDokumenSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dokumen/$id': {
      id: '/api/dokumen/$id'
      path: '/api/dokumen/$id'
      fullPath: '/api/dokumen/$id'
      preLoaderRoute: typeof ApiDokumenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/role-switch': {
      id: '/api/auth/role-switch'
      path: '/api/auth/role-switch'
      fullPath: '/api/auth/role-switch'
      preLoaderRoute: typeof ApiAuthRoleSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data/user': {
      id: '/admin/master-data/user'
      path: '/admin/master-data/user'
      fullPath: '/admin/master-data/user'
      preLoaderRoute: typeof AdminMasterDataUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data/kelengkapan': {
      id: '/admin/master-data/kelengkapan'
      path: '/admin/master-data/kelengkapan'
      fullPath: '/admin/master-data/kelengkapan'
      preLoaderRoute: typeof AdminMasterDataKelengkapanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data/kegiatan': {
      id: '/admin/master-data/kegiatan'
      path: '/admin/master-data/kegiatan'
      fullPath: '/admin/master-data/kegiatan'
      preLoaderRoute: typeof AdminMasterDataKegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data/fungsi': {
      id: '/admin/master-data/fungsi'
      path: '/admin/master-data/fungsi'
      fullPath: '/admin/master-data/fungsi'
      preLoaderRoute: typeof AdminMasterDataFungsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dokumen/$id/submit': {
      id: '/api/dokumen/$id/submit'
      path: '/submit'
      fullPath: '/api/dokumen/$id/submit'
      preLoaderRoute: typeof ApiDokumenIdSubmitRouteImport
      parentRoute: typeof ApiDokumenIdRoute
    }
    '/api/dokumen/$id/download/$lampiranIndex': {
      id: '/api/dokumen/$id/download/$lampiranIndex'
      path: '/download/$lampiranIndex'
      fullPath: '/api/dokumen/$id/download/$lampiranIndex'
      preLoaderRoute: typeof ApiDokumenIdDownloadLampiranIndexRouteImport
      parentRoute: typeof ApiDokumenIdRoute
    }
  }
}

interface DokumenIdRouteChildren {
  DokumenIdEditRoute: typeof DokumenIdEditRoute
}

const DokumenIdRouteChildren: DokumenIdRouteChildren = {
  DokumenIdEditRoute: DokumenIdEditRoute,
}

const DokumenIdRouteWithChildren = DokumenIdRoute._addFileChildren(
  DokumenIdRouteChildren,
)

interface DokumenRouteChildren {
  DokumenIdRoute: typeof DokumenIdRouteWithChildren
  DokumenAjiRoute: typeof DokumenAjiRoute
  DokumenAjuRoute: typeof DokumenAjuRoute
  DokumenSayaRoute: typeof DokumenSayaRoute
}

const DokumenRouteChildren: DokumenRouteChildren = {
  DokumenIdRoute: DokumenIdRouteWithChildren,
  DokumenAjiRoute: DokumenAjiRoute,
  DokumenAjuRoute: DokumenAjuRoute,
  DokumenSayaRoute: DokumenSayaRoute,
}

const DokumenRouteWithChildren =
  DokumenRoute._addFileChildren(DokumenRouteChildren)

interface ApiMasterFungsiRouteChildren {
  ApiMasterFungsiIdRoute: typeof ApiMasterFungsiIdRoute
}

const ApiMasterFungsiRouteChildren: ApiMasterFungsiRouteChildren = {
  ApiMasterFungsiIdRoute: ApiMasterFungsiIdRoute,
}

const ApiMasterFungsiRouteWithChildren = ApiMasterFungsiRoute._addFileChildren(
  ApiMasterFungsiRouteChildren,
)

interface ApiMasterKegiatanRouteChildren {
  ApiMasterKegiatanIdRoute: typeof ApiMasterKegiatanIdRoute
}

const ApiMasterKegiatanRouteChildren: ApiMasterKegiatanRouteChildren = {
  ApiMasterKegiatanIdRoute: ApiMasterKegiatanIdRoute,
}

const ApiMasterKegiatanRouteWithChildren =
  ApiMasterKegiatanRoute._addFileChildren(ApiMasterKegiatanRouteChildren)

interface ApiMasterKelengkapanRouteChildren {
  ApiMasterKelengkapanIdRoute: typeof ApiMasterKelengkapanIdRoute
}

const ApiMasterKelengkapanRouteChildren: ApiMasterKelengkapanRouteChildren = {
  ApiMasterKelengkapanIdRoute: ApiMasterKelengkapanIdRoute,
}

const ApiMasterKelengkapanRouteWithChildren =
  ApiMasterKelengkapanRoute._addFileChildren(ApiMasterKelengkapanRouteChildren)

interface ApiDokumenIdRouteChildren {
  ApiDokumenIdSubmitRoute: typeof ApiDokumenIdSubmitRoute
  ApiDokumenIdDownloadLampiranIndexRoute: typeof ApiDokumenIdDownloadLampiranIndexRoute
}

const ApiDokumenIdRouteChildren: ApiDokumenIdRouteChildren = {
  ApiDokumenIdSubmitRoute: ApiDokumenIdSubmitRoute,
  ApiDokumenIdDownloadLampiranIndexRoute:
    ApiDokumenIdDownloadLampiranIndexRoute,
}

const ApiDokumenIdRouteWithChildren = ApiDokumenIdRoute._addFileChildren(
  ApiDokumenIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BendaharaRoute: BendaharaRoute,
  DokumenRoute: DokumenRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  PpkRoute: PpkRoute,
  ApiMasterFungsiRoute: ApiMasterFungsiRouteWithChildren,
  ApiMasterKegiatanRoute: ApiMasterKegiatanRouteWithChildren,
  ApiMasterKelengkapanRoute: ApiMasterKelengkapanRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArsiparisIndexRoute: ArsiparisIndexRoute,
  AdminMasterDataFungsiRoute: AdminMasterDataFungsiRoute,
  AdminMasterDataKegiatanRoute: AdminMasterDataKegiatanRoute,
  AdminMasterDataKelengkapanRoute: AdminMasterDataKelengkapanRoute,
  AdminMasterDataUserRoute: AdminMasterDataUserRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRoleSwitchRoute: ApiAuthRoleSwitchRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiDokumenIdRoute: ApiDokumenIdRouteWithChildren,
  ApiDokumenSubmitRoute: ApiDokumenSubmitRoute,
  AdminMasterDataIndexRoute: AdminMasterDataIndexRoute,
  ApiDokumenIndexRoute: ApiDokumenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
